import assert from 'node:assert/strict';
import { BattlePresentation, type PresentationEvent } from '../src/battle/presentation';
import { damagePresentationAmount } from '../src/battle/damagePresentation';
import { liurenSurvivalRule, resolveDamageTransition } from '../src/battle/survivalRules';

const event = (type: PresentationEvent['type'], delta: number, before: number, options: Partial<PresentationEvent> = {}): PresentationEvent => ({
  side: 'p1', elfId: 'first', type, amount: Math.abs(delta), delta, before, after: before + delta, maxHp: 500, ...options,
});
const shown: any[] = [];
const p = new BattlePresentation(() => { if (p.popups.length) shown.push(structuredClone(p.popups[0])); }, () => true);
await p.record(event('fixed', -30, 500));
assert.equal(shown.length, 0, '粉傷先記錄，真實值已結算也不立即播放');
await p.record(event('skill', -40, 470));
assert.equal(shown[0].text, '-40');
assert.equal(p.hp.get('p1:first'), 460, '播放 HP 只扣已播放的紅傷');
await p.record(event('heal', 20, 430));
await p.record(event('true', -10, 450));
await p.record(event('percent', -5, 440));
await p.record(event('true', -15, 435));
await p.flush();
assert.deepEqual(shown.map(e => e.type), ['skill', 'fixed', 'heal', 'true']);
assert.deepEqual(shown.map(e => e.amount), [40, 35, 20, 25], '多筆白傷總額不漏掉前幾筆');
assert.equal(p.hp.get('p1:first'), 420);
assert.equal(p.popups.length, 0);
const count = shown.length;
await p.flush();
assert.equal(shown.length, count, '無額外事件時沒有空白段或假動畫');
await p.record(event('heal', 30, 420, { immediate: true, label: '藥劑回血' }));
assert.equal(shown.at(-1).text, '+30', '吃藥即時播放');
await p.record(event('skill', -10, 450, { elfId: 'second', before: 500, after: 490 }));
assert.equal(p.hp.get('p1:first'), 450);
assert.equal(p.hp.get('p1:second'), 490, '換人後不同精靈不共用播放 HP');

const lethal: any[] = [];
const q = new BattlePresentation(() => { if (q.popups.length) lethal.push(q.popups[0]); }, () => true);
await q.record(event('heal', 10, 40));
await q.record(event('fixed', -5, 50));
await q.record(event('true', -45, 45));
assert.deepEqual(lethal.map(e => e.type), ['heal', 'fixed', 'true'], '陣亡邊界依原紀錄順序播放');
assert.equal(q.hp.get('p1:first'), 0);

let notifications = 0;
const old = new BattlePresentation(() => notifications++, () => false);
const pending = old.record(event('skill', -10, 500));
await Promise.resolve();
assert.equal(old.popups.length, 1);
old.dispose();
const disposedNotifications = notifications;
await pending;
await old.record(event('heal', 50, 490));
await old.flush();
assert.equal(notifications, disposedNotifications, '卸載取消尚未完成的播放回呼');
assert.equal(old.popups.length, 0);
assert.equal(old.hp.size, 0);
const fresh = new BattlePresentation(() => {}, () => true);
assert.equal(fresh.hp.size, 0, '重來建立全新播放狀態');
assert.equal(fresh.popups.length, 0);
const freeze = resolveDamageTransition(40, 500, 127, 'true', liurenSurvivalRule());
const atZero = resolveDamageTransition(0, 500, 53, 'true', liurenSurvivalRule());
assert.equal(freeze.hp, 0); assert.equal(atZero.hp, 0);
assert.equal(freeze.alive, true); assert.equal(atZero.alive, true);
assert.equal(damagePresentationAmount('true', 127, freeze.damageApplied), 127);
assert.equal(damagePresentationAmount('true', 53, atZero.damageApplied), 53);
assert.equal(damagePresentationAmount('skill', 127, 40), 40, '非真傷維持既有數字');
const ordinary = resolveDamageTransition(40, 500, 127, 'true');
assert.equal(ordinary.hp, 0); assert.equal(ordinary.alive, false);
assert.equal(damagePresentationAmount('true', 127, ordinary.damageApplied), 127, '一般精靈超額真傷也保留原值，死亡判定不變');
const white: any[] = [];
const bounded = new BattlePresentation(() => { if (bounded.popups.length) white.push(bounded.popups[0]); }, () => true);
await bounded.record(event('true', -40, 40, { amount: 127, after: 0, alive: true }));
await bounded.record(event('true', 0, 0, { amount: 53, after: 0, alive: true }));
assert.equal(white.length, 0, '0 HP 仍存活不觸發假陣亡動畫');
await bounded.flush();
assert.equal(white.length, 1);
assert.equal(white[0].text, '-180', '白字保存兩筆原真傷，HP 凍結也不變成 -0');
assert.equal(white[0].delta, -40);
assert.equal(bounded.hp.get('p1:first'), 0, '播放 HP 不因原傷害數字低於 0');
console.log('動畫驗收：紅傷／吃藥即時、粉綠白分組、白傷總量、空段跳過、陣亡順序、身份隔離、卸載／重來清除通過。');
