import assert from 'node:assert/strict';
import { BattlePresentation, type PresentationEvent } from '../src/battle/presentation';
import { damagePresentationAmount } from '../src/battle/damagePresentation';
import { liurenSurvivalRule, resolveDamageTransition } from '../src/battle/survivalRules';

const event = (type: PresentationEvent['type'], delta: number, before: number, options: Partial<PresentationEvent> = {}): PresentationEvent => ({
  side: 'p1', elfId: 'first', type, amount: Math.abs(delta), delta, before, after: before + delta, maxHp: 500, ...options,
});
const shown: any[] = [];
const p = new BattlePresentation(() => { if (p.popups.length) shown.push(...structuredClone(p.popups)); }, () => true);
await p.record(event('fixed', -30, 500));
assert.equal(shown.length, 0, '粉傷先記錄，真實值已結算也不立即播放');
await p.record(event('skill', -40, 470));
assert.equal(shown[0].text, '-40');
assert.equal(p.hp.get('p1:first'), 460, '播放 HP 只扣已播放的紅傷');
await p.record(event('heal', 20, 430));
await p.record(event('true', -10, 450));
await p.record(event('percent', -5, 440));
await p.record(event('true', -15, 435));
await p.flush();
assert.deepEqual(shown.map(e => e.type), ['skill', 'fixed', 'true'], '固定／百分比／回血合併為體力淨變化，真傷獨立分類');
assert.deepEqual(shown.map(e => e.amount), [40, 15, 25], '淨變化 -30+20-5＝-15（粉）；多筆白傷總額不漏');
assert.equal(p.hp.get('p1:first'), 420);
assert.equal(p.popups.length, 0);
const count = shown.length;
await p.flush();
assert.equal(shown.length, count, '無額外事件時沒有空白段或假動畫');
await p.record(event('heal', 30, 420, { immediate: true, label: '藥劑回血' }));
assert.equal(shown.at(-1).text, '+30', '吃藥即時播放');
await p.record(event('skill', -10, 450, { elfId: 'second', before: 500, after: 490 }));
assert.equal(p.hp.get('p1:first'), 450);
assert.equal(p.hp.get('p1:second'), 490, '換人後不同精靈不共用播放 HP');

const lethal: any[] = [];
const q = new BattlePresentation(() => { if (q.popups.length) lethal.push(...q.popups); }, () => true);
q.setInAction(false); // 出手外（回合末等）的致死：當下結算
await q.record(event('heal', 10, 40));
await q.record(event('fixed', -5, 50));
await q.record(event('true', -45, 45));
assert.deepEqual(lethal.map(e => e.type), ['heal', 'true'], '延後紀錄致命：淨變化（+5 綠）→ 真傷');
assert.equal(q.hp.get('p1:first'), 0);

let notifications = 0;
const old = new BattlePresentation(() => notifications++, () => false);
const pending = old.record(event('skill', -10, 500));
await Promise.resolve();
assert.equal(old.popups.length, 1);
old.dispose();
const disposedNotifications = notifications;
await pending;
await old.record(event('heal', 50, 490));
await old.flush();
assert.equal(notifications, disposedNotifications, '卸載取消尚未完成的播放回呼');
assert.equal(old.popups.length, 0);
assert.equal(old.hp.size, 0);
const fresh = new BattlePresentation(() => {}, () => true);
assert.equal(fresh.hp.size, 0, '重來建立全新播放狀態');
assert.equal(fresh.popups.length, 0);
const freeze = resolveDamageTransition(40, 500, 127, 'true', liurenSurvivalRule());
const atZero = resolveDamageTransition(0, 500, 53, 'true', liurenSurvivalRule());
assert.equal(freeze.hp, 0); assert.equal(atZero.hp, 0);
assert.equal(freeze.alive, true); assert.equal(atZero.alive, true);
assert.equal(damagePresentationAmount('true', 127, freeze.damageApplied), 127);
assert.equal(damagePresentationAmount('true', 53, atZero.damageApplied), 53);
assert.equal(damagePresentationAmount('skill', 127, 40), 127, '技能傷害顯示實際傷害，不是體力變化');
assert.equal(damagePresentationAmount('fixed', 127, 40), 40, '固定傷害顯示體力變化');
const ordinary = resolveDamageTransition(40, 500, 127, 'true');
assert.equal(ordinary.hp, 0); assert.equal(ordinary.alive, false);
assert.equal(damagePresentationAmount('true', 127, ordinary.damageApplied), 127, '一般精靈超額真傷也保留原值，死亡判定不變');
const white: any[] = [];
const bounded = new BattlePresentation(() => { if (bounded.popups.length) white.push(bounded.popups[0]); }, () => true);
await bounded.record(event('true', -40, 40, { amount: 127, after: 0, alive: true }));
await bounded.record(event('true', 0, 0, { amount: 53, after: 0, alive: true }));
assert.equal(white.length, 0, '0 HP 仍存活不觸發假陣亡動畫');
await bounded.flush();
assert.equal(white.length, 1);
assert.equal(white[0].text, '-180', '白字保存兩筆原真傷，HP 凍結也不變成 -0');
assert.equal(white[0].delta, -40);
assert.equal(bounded.hp.get('p1:first'), 0, '播放 HP 不因原傷害數字低於 0');
// 淨變化為 0 不播；技能擊倒不把延後紀錄插到前面
const zero: any[] = [];
const z = new BattlePresentation(() => { if (z.popups.length) zero.push(z.popups[0]); }, () => true);
await z.record(event('fixed', -20, 100));
await z.record(event('heal', 20, 80));
await z.flush();
assert.equal(zero.length, 0, '淨變化 0 不播放');
await z.record(event('fixed', -20, 100));
await z.record(event('skill', -80, 80, { effectiveness: '克制' }));
assert.deepEqual(zero.map(e => [e.type, e.effectiveness]), [['skill', '克制']], '擊倒紅字先播，粉傷不插到前面');
await z.flush();
assert.equal(zero.length, 1, '已倒下的精靈不再播延後紀錄');
assert.equal(z.hp.get('p1:first'), 0);
// 出手外（回合開始）的技能傷害：不致死就留到回合末，與粉傷、真傷一起播；致死時當下播
const outer: any[] = [];
const o = new BattlePresentation(() => { if (o.popups.length) outer.push(...o.popups); }, () => true);
o.setInAction(false);
await o.record(event('skill', -30, 500, { effectiveness: '克制' }));
assert.equal(outer.length, 0, '回合開始的紅傷不先播');
o.setInAction(true);
await o.record(event('skill', -50, 470));
assert.deepEqual(outer.map(e => e.amount), [50], '出手紅傷先播');
await o.record(event('fixed', -10, 420));
await o.flush();
assert.deepEqual(outer.map(e => [e.type, e.amount]), [['skill', 50], ['skill', 30], ['fixed', 10]], '回合末：延後紅傷→淨變化');
o.setInAction(false);
await o.record(event('skill', -410, 410, { elfId: 'k', before: 410, after: 0 }));
assert.equal(outer.at(-1).amount, 410, '致死時當下播');
// 出手中致死的真傷：不搶在出招／紅字前面，出手結束才播
const fo: any[] = [];
const f = new BattlePresentation(() => { if (f.popups.length) fo.push(f.popups[0]); }, () => true);
f.setInAction(true);
await f.record(event('true', -100, 100, { elfId: 'z', before: 100, after: 0 }));
assert.equal(fo.length, 0, '致死真傷先不播');
await f.record(event('skill', -20, 0, { elfId: 'z', before: 0, after: 0, alive: true }));
f.setInAction(false); await f.wait();
assert.deepEqual(fo.map(e => e.type), ['skill', 'true'], '紅字先、真傷後');
console.log('動畫驗收：紅傷／吃藥即時、粉綠白分組、白傷總量、空段跳過、陣亡順序、身份隔離、卸載／重來清除通過。');

// 額外行動：不論幾次，紅字播完後只多播一次合併紅字。
const extraShown: any[] = [];
const ex = new BattlePresentation(() => { if (ex.popups.length) extraShown.push(structuredClone(ex.popups[0])); }, () => true);
await ex.record(event('skill', -50, 500));
ex.beginExtra();
await ex.record(event('skill', -20, 450, { elfId: 'first' }));
await ex.record(event('skill', -30, 430));
await ex.record(event('fixed', -5, 400));
await ex.record(event('skill', -10, 395));
assert.equal(extraShown.length, 1, '額外行動期間的紅字先收集');
await ex.endExtra();
assert.deepEqual(extraShown.map(e => [e.type, e.amount, e.label]), [['skill', 50, undefined], ['skill', 60, '額外行動']], '三次額外行動只多播一次');
await ex.flush();
assert.deepEqual(extraShown.at(-1).type, 'fixed', '額外行動的粉傷仍留到回合末');
ex.beginExtra(); await ex.endExtra();
assert.equal(extraShown.length, 3, '沒有額外行動不播空段');

// 自訂開關：關閉的通道不出現浮字，播放 HP 仍對齊結算。
const settings = { skill: true, damage: false, extra: true, potion: false, roundEnd: false };
const muted: any[] = [];
const m = new BattlePresentation(() => { if (m.popups.length) muted.push(structuredClone(m.popups[0])); }, () => true, () => settings);
await m.record(event('skill', -40, 500));
await m.record(event('heal', 10, 460, { immediate: true, label: '藥劑回血' }));
await m.record(event('true', -20, 470));
await m.flush();
assert.equal(muted.length, 0, '技能傷害／吃藥／回合末關閉時不顯示');
assert.equal(m.hp.get('p1:first'), 450, '關閉顯示仍同步體力');
m.beginExtra(); await m.record(event('skill', -15, 450)); await m.endExtra();
assert.deepEqual(muted.map(e => e.label), ['額外行動'], '額外行動開關獨立');
console.log('動畫開關與額外行動合併通過。');
