import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import React,{act} from 'react';
import { createServer } from 'vite';
const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,HTMLElement:dom.window.HTMLElement,Element:dom.window.Element,SVGElement:dom.window.SVGElement,IS_REACT_ACT_ENVIRONMENT:true,getComputedStyle:dom.window.getComputedStyle.bind(dom.window),requestAnimationFrame:(f:any)=>setTimeout(f,0),cancelAnimationFrame:clearTimeout});
(window as any).__BATTLE_FAST__=true;
const oe=console.error; console.error=(...a:any[])=>{const s=String(a[0]); if(s.includes('act(')||s.includes('Warning'))return; oe(...a);};
const {createRoot}=await import('react-dom/client');const root=createRoot(document.getElementById('root')!);
const server=await createServer({server:{middlewareMode:true},appType:'custom',logLevel:'silent'});
const wait=async(n=15)=>{for(let i=0;i<n;i++)await act(async()=>{await new Promise(r=>setTimeout(r,20))});};
try{
 const {default:Battle}=await server.ssrLoadModule('/src/components/BattleScreen.tsx');
 const {getBattleSkillRegistry}=await server.ssrLoadModule('/src/effects/battleEventRegistry.ts');
 const R=getBattleSkillRegistry();
 const ST='冰封', mode='killswap';
 R['上異常']=(c:any)=>{ c.applyStatusWithImmunityCheck('p2',ST,3); };
 R['必殺']=(c:any)=>{ c.applyTrueDamage('p2',9999999,'必殺'); };
 const mk=(id:string,hp:number,skills:string[],speed=100):any=>({id,name:id,battleId:id,type:'普通',level:100,currentHp:hp,maxHp:hp,baseStats:{hp:100,atk:100,def:100,spatk:100,spdef:100,speed},calculatedStats:{hp,atk:100,def:100,spatk:100,spdef:100,speed},statStages:{},skills:skills.map(n=>({name:n,category:'屬性',type:'普通',power:0,pp:99,maxPp:99,isSureHit:true}))});
 let d:any;
 await act(async()=>root.render(React.createElement(Battle,{initialP1Team:[mk('A',100000,['上異常','等待','必殺'],200)],initialP2Team:[mk('X',100000,['等待'],100),mk('Y',100000,['等待'],50)],p1StarterId:'A',p2StarterId:'X',battleMode:'PVP',preparedTeams:true,onBackToMenu:()=>{},onDriverInit:(x:any)=>d=x})));
 await wait(5);
 const show=(t:string)=>{const s=d.getSyncState(); console.log(t,'phase',s.phase,'turn',s.turnNumber,'p2 active',s.p2.name, s.p2Team.map((e:any)=>e.name+':'+JSON.stringify((e.effects||[]).map((x:any)=>x.id+x.duration))).join(' | '));};
 const turn=async(p1:number, p2:'skill'|number)=>{ const s=d.getSyncState(); if(s.phase.startsWith('forced')){const st=s; const idx=st.p2Team.findIndex((e:any,i:number)=>i!==st.p2ActiveIndex&&e.currentHp>0); await act(async()=>d.onSwitchElf('p2',idx)); await wait(20);} await act(async()=>{ d.onSkillSelect('p1',d.getSyncState().p1.skills[p1]); if(p2==='skill') d.onSkillSelect('p2',s.p2.skills[0]); else d.onSwitchElf('p2',p2); }); await wait(25);
   let st=d.getSyncState(); if(st.phase.startsWith('forced_switch')){ const idx=st.p2Team.findIndex((e:any,i:number)=>i!==st.p2ActiveIndex&&e.currentHp>0); await act(async()=>d.onSwitchElf('p2',idx)); await wait(20);} };
 const fx=(n:string)=>{const e=d.getSyncState().p2Team.find((x:any)=>x.name===n); return (e.effects||[]).map((x:any)=>x.id+x.duration).join(',');};
 await turn(0,'skill'); assert.equal(fx('X'),'冰封2');
 await turn(1,1); assert.equal(d.getSyncState().p2.name,'Y'); assert.equal(fx('X'),'冰封2','場下不扣');
 await turn(2,'skill'); assert.equal(d.getSyncState().p2.name,'X','死切換回 X');
 assert.equal(fx('X'),'冰封2','死切上場的精靈不吃本回合的回合結束');
 await turn(1,'skill'); assert.equal(fx('X'),'冰封1');
 await turn(1,'skill'); assert.equal(fx('X'),'凍傷3','到期才轉化');
 console.log('死亡換人：回合結束先於換人、新上場精靈異常不提前扣減／轉化通過');
} finally { await server.close(); process.exit(0); }
