import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { createRequire } from 'node:module';
const { waitForOwnServer } = createRequire(import.meta.url)('../electron/serverProcess.cjs');
const makeChild = () => Object.assign(new EventEmitter(), { stdout: new EventEmitter() });
const child = makeChild();
let settled = false;
const ready = waitForOwnServer(child).then(port => { settled = true; return port; });
await Promise.resolve();
assert.equal(settled, false, '不能因為另一個伺服器已開啟就宣稱自己啟動完成');
child.stdout.emit('data', Buffer.from('Port 3000 busy, switched to 3001\nServer running on http://local'));
assert.equal(settled, false);
child.stdout.emit('data', Buffer.from('host:30'));
assert.equal(settled, false, '不能把尚未接收完整的連接埠當成就緒');
child.stdout.emit('data', Buffer.from('01\n'));
assert.equal(await ready, 3001);
assert.equal(child.listenerCount('exit'), 0);
const failed = makeChild();
const failedReady = waitForOwnServer(failed);
failed.emit('exit', 1);
await assert.rejects(failedReady, /啟動失敗/);
assert.equal(failed.stdout.listenerCount('data'), 0);
await assert.rejects(waitForOwnServer(makeChild(), 5), /逾時/);
console.log('Electron 啟動：自己就緒、埠衝突改用正確埠、退出與逾時清理通過。');
