import assert from 'node:assert/strict';
import { prepareBattle, settleBattle, moveRun, saveRun, loadRun, consumePotion, recruitRun, RUN_KEY } from '../src/modes/interstellar/runState';
const base: any = { runId:'r', revision:0, currentLayer:1, fuel:5, maxFuel:10, saerBeans:200, earnedExp:0, selectedModifiers:[], collectibles:[], vouchers:{A:0,B:0,C:1,S:0}, layers:[{id:1,nodes:[{id:'a',type:'elite',status:'current',connections:['b']},{id:'b',type:'shop',status:'unvisited',connections:[]}]}] };
const pending = prepareBattle(base, 'battle', [0,0,0,0]);
const result = settleBattle(pending, 'battle', 'p1');
assert.equal(result.saerBeans,400); assert.equal(result.earnedExp,100);
assert.equal(result.vouchers.A,1); assert.equal(result.collectibles.length,1);
assert.equal(settleBattle(result,'battle','p1'),result);
assert.equal(settleBattle(pending,'other','p1'),pending);
assert.equal(settleBattle(pending,'battle','p2').fuel,3);
assert.equal(moveRun(base,'nope'),null);
assert.equal(moveRun({...base,fuel:0},'b'),null);
assert.equal(moveRun(base,'b')?.fuel,4);
const store = new Map<string,string>(); const storage={getItem:(k:string)=>store.get(k)??null,setItem:(k:string,v:string)=>{store.set(k,v)}};
saveRun(storage,pending); assert.equal(consumePotion(storage,'r','battle',2),true);
assert.equal(loadRun(storage)?.potionUsage,1);
saveRun(storage,base); assert.equal(loadRun(storage)?.pendingBattle.id,'battle');
assert.equal(consumePotion(storage,'r','wrong',2),false);
assert.equal(settleBattle(pending,'battle','p2').layers[0].nodes[0].occupied,undefined);
assert.equal(settleBattle(pending,'battle','exit').saerBeans,200);
assert.equal(settleBattle(pending,'battle','draw').fuel,5);
assert.equal(settleBattle({...pending,piratePrincipal:300},'battle','p1').saerBeans,700);
assert.equal(settleBattle({...pending,piratePrincipal:300},'battle','p2').saerBeans,200);
const boss=prepareBattle({...base,layers:[{id:1,nodes:[{id:'boss',status:'current',type:'boss'}]}]},'boss',[0,0,0,0]);
assert.equal(settleBattle(boss,'boss','p1').currentLayer,2);assert.equal(settleBattle(boss,'boss','p1').fuel,8);
const sixth=prepareBattle({...base,currentLayer:6,layers:[{id:6,nodes:[{id:'boss',status:'current',type:'boss'}]}]},'boss6',[0,0,0,0]);
assert.equal(settleBattle(sixth,'boss6','p1').currentLayer,6);
const recruitment={...base,diamonds:5,runElves:[]};
assert.equal(recruitRun(recruitment,'C',{id:'new'},6,-1),null);
assert.equal(recruitment.vouchers.C,1);
assert.equal(recruitRun(recruitment,'C',{id:'new'},2,-1)?.diamonds,3);
assert.equal(recruitRun(recruitment,'C',{id:'new'},2,-1)?.vouchers.C,0);
assert.equal(recruitRun({...recruitment,runElves:Array(6).fill({})},'C',{id:'new'},0,-1),null);
storage.setItem(RUN_KEY,'{broken');assert.throws(()=>saveRun(storage,base),/存檔損壞/);assert.equal(storage.getItem(RUN_KEY),'{broken');
console.log('星際持久結算／去重／藥劑／移動測試通過');
