const fs = require('fs');
const path = require('path');

// Basic default codex generator template mapping
const defaultTemplates = [
  { id: "0001", template: "給予對方損傷的一半恢復自身等量體力", paramCount: 0, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: true, target: "both", targetInferred: false, polarity: "MIXED", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: true, reviewReason: "雙極:需拆[對手負]+[自身正]子效果" },
  { id: "0002", template: "對方體力小於1/2時威力翻倍", paramCount: 0, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: false, target: "opponent", targetInferred: false, polarity: "NEUTRAL", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: false, reviewReason: "" },
  { id: "0003", template: "解除自身的能力下降狀態（BOSS有效）", paramCount: 0, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: false, target: "self", targetInferred: false, polarity: "NEUTRAL", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: false, reviewReason: "" },
  { id: "0004", template: "技能使用成功時，{1}%改變自身{0}等級{2}（BOSS有效）", paramCount: 3, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: false, target: "self", targetInferred: false, polarity: "NEUTRAL", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: false, reviewReason: "" },
  { id: "0005", template: "技能使用成功時，{1}%改變對手{0}等級{2}（BOSS有效）", paramCount: 3, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: false, target: "opponent", targetInferred: false, polarity: "NEUTRAL", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: false, reviewReason: "" },
  { id: "0006", template: "對方所受技能傷害的1/{0}會以同屬性技能傷害形式反彈給自己", paramCount: 1, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: true, target: "both", targetInferred: false, polarity: "MIXED", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: true, reviewReason: "雙極:需拆[對手負]+[自身正]子效果" },
  { id: "0010", template: "命中後{0}%令對方麻痺", paramCount: 1, era: "modern", role: "attached", node: "on_hit", damageType: null, counterKind: null, isDual: false, target: "opponent", targetInferred: false, polarity: "NEGATIVE", contexts: ["skill"], namedStatus: true, clarity: "clear", needsReview: false, reviewReason: "" },
  { id: "0011", template: "命中後{0}%令對方中毒（BOSS有效）", paramCount: 1, era: "modern", role: "attached", node: "on_hit", damageType: null, counterKind: null, isDual: false, target: "opponent", targetInferred: false, polarity: "NEGATIVE", contexts: ["skill"], namedStatus: true, clarity: "clear", needsReview: false, reviewReason: "" },
  { id: "0012", template: "命中後{0}%令對方燒傷（BOSS有效）", paramCount: 1, era: "modern", role: "attached", node: "on_hit", damageType: null, counterKind: null, isDual: false, target: "opponent", targetInferred: false, polarity: "NEGATIVE", contexts: ["skill"], namedStatus: true, clarity: "clear", needsReview: false, reviewReason: "" },
  { id: "0013", template: "{0}回合吸取對方最大體力的1/8(對草系無效)", paramCount: 1, era: "legacy", role: "innate", node: null, damageType: null, counterKind: "turn_effect", isDual: true, target: "both", targetInferred: false, polarity: "MIXED", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: true, reviewReason: "雙極:需拆[對手負]+[自身正]子效果" },
  { id: "0029", template: "額外附加{0}點固定傷害（BOSS有效）", paramCount: 1, era: "modern", role: "attached", node: null, damageType: "fixed", counterKind: null, isDual: false, target: "self", targetInferred: true, polarity: "NEUTRAL", contexts: ["skill"], namedStatus: false, clarity: "clear", needsReview: false, reviewReason: "" },
  { id: "0043", template: "恢復自身最大體力的1/{0}", paramCount: 1, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: false, target: "self", targetInferred: false, polarity: "POSITIVE", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: false, reviewReason: "" },
  { id: "0048", template: "{0}回合內免疫所有受到的異常狀態（BOSS有效）", paramCount: 1, era: "legacy", role: "attached", node: null, damageType: null, counterKind: "turn_effect", isDual: false, target: "self", targetInferred: true, polarity: "POSITIVE", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: false, reviewReason: "" },
  { id: "0180", template: "消除對手回合類效果", paramCount: 0, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: false, target: "opponent", targetInferred: false, polarity: "NEGATIVE", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: true, reviewReason: "回合類效果互動" },
  { id: "0870", template: "吸取對手{0}點體力", paramCount: 1, era: "legacy", role: "innate", node: null, damageType: null, counterKind: null, isDual: true, target: "both", targetInferred: false, polarity: "MIXED", contexts: ["skill"], namedStatus: false, clarity: "vague", needsReview: true, reviewReason: "雙極:需拆[對手負]+[自身正]子效果" },
  { id: "1005", template: "恢復自身最大體力的1/{0}並造成等量百分比傷害（BOSS有效）", paramCount: 1, era: "modern", role: "innate", node: null, damageType: "percent", counterKind: null, isDual: false, target: "self", targetInferred: false, polarity: "POSITIVE", contexts: ["skill"], namedStatus: false, clarity: "clear", needsReview: false, reviewReason: "" },
  { id: "1528", template: "附加{0}點真實傷害", paramCount: 1, era: "modern", role: "attached", node: null, damageType: "true", counterKind: null, isDual: false, target: "self", targetInferred: true, polarity: "NEUTRAL", contexts: ["skill"], namedStatus: false, clarity: "clear", needsReview: false, reviewReason: "" }
];

console.log("Sample default templates loaded:", defaultTemplates.length);
